# 모든 레코드 조회
SELECT * FROM ANIMAL_INS
ORDER BY ANIMAL_ID;

# 역순 정렬
SELECT NAME, DATETIME FROM ANIMAL_INS
ORDER BY ANIMAL_ID DESC;

# 아픈 동물 찾기
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS
WHERE INTAKE_CONDITION="Sick"
ORDER BY ANIMAL_ID;


# 어린 동물 찾기
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS
WHERE INTAKE_CONDITION!="Aged"
ORDER BY ANIMAL_ID;

# 동물의 아이디와 이름
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS
ORDER BY ANIMAL_ID;

# 여러 기준으로 정렬하기
SELECT ANIMAL_ID, NAME, DATETIME FROM ANIMAL_INS
ORDER BY NAME ASC, DATETIME DESC;

# 상위 N개 레코드
SELECT NAME FROM ANIMAL_INS
ORDER BY DATETIME LIMIT 1;

# 최댓값 구하기
SELECT DATETIME FROM ANIMAL_INS
ORDER BY DATETIME DESC LIMIT 1;

SELECT MAX(DATETIME) FROM ANIMAL_INS;


# 최소값 구하기
SELECT DATETIME FROM ANIMAL_INS
ORDER BY DATETIME LIMIT 1;

SELECT MIN(DATETIME) FROM ANIMAL_INS;


# 동물 수 구하기
SELECT COUNT(*) FROM ANIMAL_INS


# 중복 제거하기
SELECT COUNT(DISTINCT NAME) FROM ANIMAL_INS
WHERE NAME IS NOT NULL


# 고양이와 개는 몇 마리 있을까?
SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE) FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE ORDER BY ANIMAL_TYPE

# 이름이 없는 동물의 아이디
SELECT ANIMAL_ID FROM ANIMAL_INS
WHERE NAME IS NULL ORDER BY ANIMAL_ID

# 이름이 있는 동물의 아이디
SELECT ANIMAL_ID FROM ANIMAL_INS
WHERE NAME IS NOT NULL ORDER BY ANIMAL_ID